build:
  environment:
    php: 7.2.24
    timezone: Europe/Paris

  nodes:
    tests:
      environment:
        docker: true

      services:
        mysql: 5.7

      dependencies:
        before:
#          - sudo service mysql stop
          - ./.github/run-mysql.sh

      tests:
        override:
          - command: composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover
