name: Build

on:
  push:
    branches: [ '[1-9].[0-9]+' ]
  pull_request:
    branches: [ '[1-9].[0-9]+' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
    name: PHP ${{ matrix.php-versions }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Paris"
    
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: json
        ini-values: date.timezone=Europe/Paris
    - name: Check PHP Version
      run: php -v

    - name: Install MySQL
      run: ./.github/run-mysql.sh

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: composer run-script tests

  analysis:
    name: Analysis
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Paris"

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: json
        ini-values: date.timezone=Europe/Paris

    - name: Install MySQL
      run: ./.github/run-mysql.sh

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run type coverage
      run: composer run-script psalm

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Europe/Paris"

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: json
        ini-values: date.timezone=Europe/Paris

    - name: Install MySQL
      run: ./.github/run-mysql.sh

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test coverage
      run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
